-- Cursor-style AI credits: model mode, auto top-up, Stripe billing fields

ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "aiModelMode" TEXT NOT NULL DEFAULT 'AUTO';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "premiumModelId" TEXT NOT NULL DEFAULT 'gpt-4.1';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "autoTopUpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "autoTopUpThresholdCredits" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "autoTopUpPackId" TEXT NOT NULL DEFAULT 'pack_25';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "stripeCustomerId" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "stripePaymentMethodId" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "autoTopUpLastTriggeredAt" TIMESTAMP(3);

ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "aiModelMode" TEXT NOT NULL DEFAULT 'AUTO';
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "premiumModelId" TEXT NOT NULL DEFAULT 'gpt-4.1';
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "autoTopUpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "autoTopUpThresholdCredits" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "autoTopUpPackId" TEXT NOT NULL DEFAULT 'pack_25';
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "stripeCustomerId" TEXT;
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "stripePaymentMethodId" TEXT;
ALTER TABLE "ConsumerProfile" ADD COLUMN IF NOT EXISTS "autoTopUpLastTriggeredAt" TIMESTAMP(3);

ALTER TABLE "UserPreferences" ADD COLUMN IF NOT EXISTS "aiModelMode" TEXT NOT NULL DEFAULT 'AUTO';
ALTER TABLE "UserPreferences" ADD COLUMN IF NOT EXISTS "premiumModelId" TEXT NOT NULL DEFAULT 'gpt-4.1';
ALTER TABLE "UserPreferences" ADD COLUMN IF NOT EXISTS "autoTopUpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserPreferences" ADD COLUMN IF NOT EXISTS "autoTopUpThresholdCredits" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "UserPreferences" ADD COLUMN IF NOT EXISTS "autoTopUpPackId" TEXT NOT NULL DEFAULT 'pack_25';
