import type {
  User,
  Client,
  Matter,
  Task,
  Document,
  Invoice,
  TrustAccount,
  TrustTransaction,
  Notification,
  AutomationRule,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'john.doe@lawfirm.com',
    name: 'John Doe',
    role: 'FIRM_OWNER',
    firmId: 'firm-1',
    avatar: undefined,
  },
  {
    id: 'user-2',
    email: 'jane.smith@lawfirm.com',
    name: 'Jane Smith',
    role: 'ADVOCATE',
    firmId: 'firm-1',
  },
  {
    id: 'user-3',
    email: 'mike.jones@lawfirm.com',
    name: 'Mike Jones',
    role: 'PARALEGAL',
    firmId: 'firm-1',
  },
  {
    id: 'user-4',
    email: 'sarah.wilson@lawfirm.com',
    name: 'Sarah Wilson',
    role: 'ACCOUNTANT',
    firmId: 'firm-1',
  },
]

// Mock Clients
export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'Acme Corporation',
    type: 'COMPANY',
    email: 'contact@acme.com',
    phone: '+1-555-0101',
    address: {
      street: '123 Business St',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      zipCode: '10001',
    },
    kycStatus: 'VERIFIED',
    tags: ['corporate', 'ongoing'],
    portalEnabled: true,
    notificationsEnabled: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'client-2',
    name: 'John Smith',
    type: 'INDIVIDUAL',
    email: 'john.smith@email.com',
    phone: '+1-555-0102',
    address: {
      street: '456 Residential Ave',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      zipCode: '90001',
    },
    kycStatus: 'UPLOADED',
    tags: ['conveyancing'],
    portalEnabled: false,
    notificationsEnabled: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'client-3',
    name: 'Green Earth Foundation',
    type: 'NGO',
    email: 'info@greenearth.org',
    phone: '+1-555-0103',
    kycStatus: 'MISSING',
    tags: ['non-profit'],
    portalEnabled: true,
    notificationsEnabled: false,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
]

// Mock Matters
export const mockMatters: Matter[] = [
  {
    id: 'matter-1',
    ref: 'MAT-2024-001',
    title: 'Acme Corp - M&A Transaction',
    clientId: 'client-1',
    client: mockClients[0],
    type: 'CORPORATE',
    stage: 'IN_PROGRESS',
    status: 'ACTIVE',
    advocateId: 'user-2',
    advocate: mockUsers[1],
    adminId: 'user-3',
    admin: mockUsers[2],
    parties: [
      { id: 'p1', name: 'Acme Corporation', role: 'Client', type: 'CLIENT' },
      { id: 'p2', name: 'TechCo Inc', role: 'Acquirer', type: 'OPPOSING' },
    ],
    keyDates: [
      { id: 'kd1', label: 'Due Diligence Deadline', date: new Date('2024-03-15'), type: 'FILING' },
      { id: 'kd2', label: 'Closing Date', date: new Date('2024-04-30'), type: 'OTHER' },
    ],
    nextDeadline: new Date('2024-03-15'),
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-18'),
  },
  {
    id: 'matter-2',
    ref: 'MAT-2024-002',
    title: 'Smith - Property Purchase',
    clientId: 'client-2',
    client: mockClients[1],
    type: 'CONVEYANCING',
    stage: 'OPEN',
    status: 'ACTIVE',
    advocateId: 'user-2',
    advocate: mockUsers[1],
    parties: [
      { id: 'p3', name: 'John Smith', role: 'Buyer', type: 'CLIENT' },
      { id: 'p4', name: 'Property Seller LLC', role: 'Seller', type: 'OPPOSING' },
    ],
    keyDates: [
      { id: 'kd3', label: 'Contract Signing', date: new Date('2024-03-01'), type: 'OTHER' },
    ],
    nextDeadline: new Date('2024-03-01'),
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-15'),
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Review Due Diligence Documents',
    description: 'Complete review of all financial documents',
    matterId: 'matter-1',
    matter: mockMatters[0],
    clientId: 'client-1',
    client: mockClients[0],
    dueDate: new Date('2024-02-25'),
    priority: 'HIGH',
    status: 'PENDING',
    assigneeId: 'user-2',
    assignee: mockUsers[1],
    watcherIds: ['user-1'],
    category: 'REVIEW',
    dependencies: [],
    createdAt: new Date('2024-02-18'),
    updatedAt: new Date('2024-02-18'),
  },
  {
    id: 'task-2',
    title: 'Prepare Purchase Agreement',
    matterId: 'matter-2',
    matter: mockMatters[1],
    clientId: 'client-2',
    client: mockClients[1],
    dueDate: new Date('2024-02-20'),
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    assigneeId: 'user-2',
    assignee: mockUsers[1],
    watcherIds: [],
    category: 'DRAFTING',
    dependencies: [],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-19'),
  },
  {
    id: 'task-3',
    title: 'Complete KYC Verification',
    clientId: 'client-3',
    client: mockClients[2],
    dueDate: new Date('2024-02-22'),
    priority: 'STANDARD',
    status: 'PENDING',
    assigneeId: 'user-3',
    assignee: mockUsers[2],
    watcherIds: [],
    category: 'COMPLIANCE',
    dependencies: [],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'task-4',
    title: 'File Court Documents',
    matterId: 'matter-1',
    matter: mockMatters[0],
    dueDate: new Date('2024-02-19'),
    priority: 'CRITICAL',
    status: 'OVERDUE',
    assigneeId: 'user-2',
    assignee: mockUsers[1],
    watcherIds: ['user-1'],
    category: 'FILING',
    dependencies: ['task-1'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-19'),
  },
]

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    name: 'Due Diligence Report.pdf',
    type: 'PDF',
    matterId: 'matter-1',
    matter: mockMatters[0],
    clientId: 'client-1',
    client: mockClients[0],
    uploadedBy: 'user-2',
    uploadedAt: new Date('2024-02-15'),
    size: 2048576,
    version: 1,
    versions: [
      { version: 1, uploadedAt: new Date('2024-02-15'), uploadedBy: 'user-2', size: 2048576 },
    ],
    approvedForPortal: false,
  },
  {
    id: 'doc-2',
    name: 'Purchase Agreement Draft.docx',
    type: 'DOCX',
    matterId: 'matter-2',
    matter: mockMatters[1],
    clientId: 'client-2',
    client: mockClients[1],
    uploadedBy: 'user-2',
    uploadedAt: new Date('2024-02-18'),
    size: 512000,
    version: 2,
    versions: [
      { version: 1, uploadedAt: new Date('2024-02-15'), uploadedBy: 'user-2', size: 450000 },
      { version: 2, uploadedAt: new Date('2024-02-18'), uploadedBy: 'user-2', size: 512000 },
    ],
    approvedForPortal: true,
    approvedBy: 'user-1',
    approvedAt: new Date('2024-02-18'),
  },
]

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    number: 'INV-2024-001',
    clientId: 'client-1',
    client: mockClients[0],
    matterId: 'matter-1',
    matter: mockMatters[0],
    status: 'SENT',
    issueDate: new Date('2024-02-01'),
    dueDate: new Date('2024-03-01'),
    lineItems: [
      { id: 'li1', description: 'Legal Services - M&A Transaction', quantity: 40, rate: 500, amount: 20000 },
      { id: 'li2', description: 'Due Diligence Review', quantity: 15, rate: 400, amount: 6000 },
    ],
    subtotal: 26000,
    tax: 2600,
    total: 28600,
    paidAmount: 0,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'inv-2',
    number: 'INV-2024-002',
    clientId: 'client-2',
    client: mockClients[1],
    matterId: 'matter-2',
    matter: mockMatters[1],
    status: 'PAID',
    issueDate: new Date('2024-02-05'),
    dueDate: new Date('2024-02-20'),
    lineItems: [
      { id: 'li3', description: 'Conveyancing Services', quantity: 10, rate: 300, amount: 3000 },
    ],
    subtotal: 3000,
    tax: 300,
    total: 3300,
    paidAmount: 3300,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-18'),
  },
]

// Mock Trust Accounts
export const mockTrustAccounts: TrustAccount[] = [
  {
    id: 'trust-1',
    clientId: 'client-1',
    client: mockClients[0],
    matterId: 'matter-1',
    matter: mockMatters[0],
    balance: 50000,
    transactions: [
      {
        id: 'tt-1',
        accountId: 'trust-1',
        type: 'DEPOSIT',
        amount: 50000,
        description: 'Initial retainer deposit',
        status: 'COMPLETED',
        requestedBy: 'user-1',
        approvedBy: 'user-1',
        approvedAt: new Date('2024-01-20'),
        createdAt: new Date('2024-01-20'),
      },
    ],
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'TASK_OVERDUE',
    title: 'Overdue Task',
    message: 'File Court Documents is overdue',
    userId: 'user-2',
    read: false,
    link: '/app/tasks/task-4',
    createdAt: new Date('2024-02-19'),
  },
  {
    id: 'notif-2',
    type: 'TASK_DUE',
    title: 'Task Due Today',
    message: 'Prepare Purchase Agreement is due today',
    userId: 'user-2',
    read: false,
    link: '/app/tasks/task-2',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'notif-3',
    type: 'KYC_EXPIRED',
    title: 'KYC Expired',
    message: 'Green Earth Foundation KYC documents have expired',
    userId: 'user-1',
    read: true,
    link: '/app/clients/client-3',
    createdAt: new Date('2024-02-18'),
  },
]

// Mock Automation Rules
export const mockAutomationRules: AutomationRule[] = [
  {
    id: 'rule-1',
    name: 'KYC Missing Reminders',
    enabled: true,
    trigger: 'CLIENT_CREATED',
    conditions: { kycStatus: 'MISSING' },
    actions: { type: 'CREATE_TASK', assignTo: 'ADMIN' },
  },
  {
    id: 'rule-2',
    name: 'Task Overdue Escalations',
    enabled: true,
    trigger: 'TASK_OVERDUE',
    conditions: { priority: 'CRITICAL' },
    actions: { type: 'NOTIFY', recipients: ['ADVOCATE', 'FIRM_OWNER'] },
  },
  {
    id: 'rule-3',
    name: 'Invoice Overdue Reminders',
    enabled: true,
    trigger: 'INVOICE_OVERDUE',
    conditions: {},
    actions: { type: 'SEND_EMAIL', template: 'invoice_overdue' },
  },
]

