/**
 * Unified AI task types — shared by gateway, credit costs, copilot, and model router.
 */
export const AI_TASK_TYPES = {
  ISSUE_CHECKER: 'ISSUE_CHECKER',
  CONSUMER_FULL_REPORT: 'CONSUMER_FULL_REPORT',
  CONSUMER_ISSUE_TRIAGE: 'CONSUMER_ISSUE_TRIAGE',
  DOCUMENT_EXPLAINER: 'DOCUMENT_EXPLAINER',
  LAWYER_MATTER_QA: 'LAWYER_MATTER_QA',
  LEGAL_RESEARCH: 'LEGAL_RESEARCH',
  STRATEGY_MEMO: 'STRATEGY_MEMO',
  DOCUMENT_DRAFT: 'DOCUMENT_DRAFT',
  MATTER_SUMMARY: 'MATTER_SUMMARY',
  OPPONENT_ANALYZER: 'OPPONENT_ANALYZER',
  OPPONENT_FILING_ANALYSIS: 'OPPONENT_FILING_ANALYSIS',
  EVIDENCE_GAP: 'EVIDENCE_GAP',
  DEADLINE_AGENT: 'DEADLINE_AGENT',
  BILLING_RECOVERY: 'BILLING_RECOVERY',
  DOCUMENT_CLASSIFICATION: 'DOCUMENT_CLASSIFICATION',
  CITATION_CHECK: 'CITATION_CHECK',
  DOCUMENT_SUMMARY: 'DOCUMENT_SUMMARY',
  MATTER_KICKOFF: 'MATTER_KICKOFF',
  CASE_OUTCOME_ANALYSIS: 'CASE_OUTCOME_ANALYSIS',
} as const;

export type AiTaskType = (typeof AI_TASK_TYPES)[keyof typeof AI_TASK_TYPES];

export const COPILOT_TOOL_TASK_MAP: Record<string, AiTaskType> = {
  summarize_matter: AI_TASK_TYPES.MATTER_SUMMARY,
  legal_research_memo: AI_TASK_TYPES.LEGAL_RESEARCH,
  draft_document: AI_TASK_TYPES.DOCUMENT_DRAFT,
  suggest_next_steps: AI_TASK_TYPES.LAWYER_MATTER_QA,
};
